"""
Leads — crystallization + enrichment pipeline.

Two stages:
  1. crystallize_leads()  — converts causal chain hops into concrete call sheets (LeadSheet)
  2. run_lead_gen()       — enriches lead sheets with contacts, emails, person profiles

Previously split across lead_crystallizer.py and lead_gen.py.
"""
import asyncio
import hashlib
import logging
from typing import Any, List, Literal

from pydantic import BaseModel, Field

from app.agents.deps import AgentDeps

logger = logging.getLogger(__name__)


# ── Company name vs. description guard ────────────────────────────────────────
# LLMs in the causal council and company resolution steps sometimes return
# segment descriptions ("Mid-size electrolyser manufacturers in India") instead
# of actual company names ("Tata Power Solar").  This validator catches those.

# Words that almost never appear in real company names but frequently appear
# in segment/type descriptions generated by the LLM.
_DESCRIPTOR_WORDS: frozenset[str] = frozenset({
    # Size / segment qualifiers
    "mid-size", "midsize", "mid-market", "small-scale", "large-scale",
    "tier-1", "tier-2", "tier-3", "top-tier",
    # Plural business-type nouns (real names use singular or are proper nouns)
    "companies", "providers", "manufacturers", "suppliers", "distributors",
    "exporters", "importers", "integrators", "contractors", "subcontractors",
    "startups", "firms", "vendors", "lenders", "operators", "developers",
    "consultants", "retailers", "wholesalers", "processors", "aggregators",
    # Descriptive verbs / adjectives that leak from LLM segment descriptions
    "integrating", "specializing", "focusing", "serving", "targeting",
    "excluding", "relying", "providing",
    # Structural phrases
    "employees", "non-top", "end-users",
})

# Phrases (multi-word) that signal a description, not a name.
_DESCRIPTOR_PHRASES: tuple[str, ...] = (
    "based in", "-based ", "focused on", "engaged in", "operating in",
    "catering to", "dealing in", "involved in", "working in",
    "operations and", "partners in", "direct commercial",
    "100-500 employees", "50-150 employees", "50-200 employees",
    "50-300 employees", "50-500 employees", "500-1000 employees",
    "200-500 employees", "100-300 employees",
)


def is_company_description(name: str) -> bool:
    """Return True if *name* looks like a segment description rather than a real company name.

    Heuristics (any match → True):
      1. Length > 8 words  (real company names are rarely that long)
      2. Contains parenthetical qualifiers like "(excluding …)"
      3. Contains known descriptor words (see _DESCRIPTOR_WORDS)
      4. Contains known descriptor phrases (see _DESCRIPTOR_PHRASES)
      5. Starts with an adjective/size qualifier followed by a plural noun

    Examples that should return True:
      "Mid-size electrolyser manufacturers in India integrating new advanced electrodes"
      "Loan origination and credit assessment technology providers"
      "IT services firms focused on AI implementation for BFSI"
      "Cloud infrastructure providers India 100-500 employees"

    Examples that should return False:
      "Infinite Uptime"
      "Ramco Systems"
      "GEAR - Gemini Equipment and Rentals Pvt. Ltd."
      "Blue Dart Express"
    """
    if not name or not name.strip():
        return True

    clean = name.strip()

    # Heuristic 1: word count (very long names are descriptions)
    words = clean.split()
    if len(words) > 8:
        return True

    lower = clean.lower()

    # Heuristic 2: parenthetical qualifiers — "(excluding …)", "(multiple …)", "(non-…)"
    if "(" in clean:
        import re
        paren_content = re.findall(r'\(([^)]+)\)', clean)
        for pc in paren_content:
            pcl = pc.lower().strip()
            if any(pcl.startswith(kw) for kw in ("excluding", "multiple", "non-", "non ", "approx", "various")):
                return True

    # Heuristic 3: descriptor word check
    # Tokenize on whitespace and hyphens for matching
    tokens = set(lower.replace(",", " ").replace("(", " ").replace(")", " ").split())
    if tokens & _DESCRIPTOR_WORDS:
        return True

    # Heuristic 4: descriptor phrase check
    for phrase in _DESCRIPTOR_PHRASES:
        if phrase in lower:
            return True

    # Heuristic 5: starts with "Top N" pattern (e.g. "Top 8 Wholesale Phone Distributors")
    if lower.startswith("top ") and len(words) >= 3:
        try:
            int(words[1])
            return True  # "Top <number> ..."
        except (ValueError, IndexError):
            pass

    return False


# ── Lead sheet schema ─────────────────────────────────────────────────────────

class LeadSheet(BaseModel):
    """One concrete lead — everything a salesperson needs to make the call."""

    # Company identity
    company_name: str               # "Kama Jewellery Pvt Ltd"
    company_cin: str = ""           # "U36912GJ2001PTC039001" (from MCA)
    company_state: str = ""         # "Gujarat"
    company_city: str = ""          # "Rajkot"
    company_size_band: str = ""     # "sme" | "mid"
    company_category: str = ""      # "Company limited by shares"
    lei_id: str = ""                # Global LEI (future: GLEIF data)

    # Lead context
    hop: int                        # 1 = direct, 2 = buyer/supplier, 3 = downstream
    lead_type: Literal["pain", "opportunity", "risk", "intelligence"]
    trend_title: str                # "Steel import duty raised 15%"
    event_type: str = ""            # "trade_policy", "supply_chain", etc.

    # Sales content (what the rep says)
    contact_role: str               # "VP Procurement / Head of Sourcing"
    trigger_event: str              # "Steel import duty raised 15% on 2026-02-24"
    pain_point: str                 # "Input costs will rise ~15% in 4-6 weeks"
    service_pitch: str              # "Should-cost analysis + alternative sourcing"
    opening_line: str               # Ready-to-use first sentence for the call/email
    urgency_weeks: int = 4          # How quickly does this impact materialize?
    confidence: float = 0.7

    # Chain-of-thought carried from CausalCouncil reasoning
    reasoning: str = ""

    # Company-specific recent news
    company_news: list[dict] = Field(default_factory=list, description="Recent news about this company")

    # Self-learning signals
    data_sources: list[str] = []    # ["mca_kb", "bm25_article", "causal_inference"]
    oss_score: float = 0.0          # OSS of source synthesis (for source bandit)


# ── Contact role and service pitch mappings ───────────────────────────────────

_CONTACT_ROLES: dict[str, str] = {
    "supply_chain":  "VP Procurement / Head of Sourcing / CSCO",
    "price_change":  "CFO / VP Finance / Head of Treasury",
    "regulation":    "Compliance Head / VP Legal / Regulatory Affairs Director",
    "trade_policy":  "CEO / MD / Head of International Trade",
    "m_and_a":       "CEO / CFO / VP Strategy",
    "technology":    "CTO / VP Engineering / Chief Digital Officer",
    "labor":         "CHRO / VP HR / Head of Industrial Relations",
    "infrastructure": "COO / VP Operations / Head of Projects",
    "general":       "CEO / Managing Director",
}

_SERVICES: dict[tuple[str, str], str] = {
    ("pain", "supply_chain"):     "Should-cost analysis + alternative sourcing strategy",
    ("pain", "price_change"):     "Commodity price risk assessment + hedging strategy",
    ("pain", "regulation"):       "Regulatory compliance roadmap + gap analysis",
    ("pain", "trade_policy"):     "Trade impact assessment + mitigation playbook",
    ("pain", "infrastructure"):   "Project delay risk analysis + critical path review",
    ("opportunity", "supply_chain"): "Market share expansion intelligence + supplier mapping",
    ("opportunity", "price_change"): "Procurement timing + forward-buying strategy",
    ("opportunity", "trade_policy"): "Export opportunity intelligence + market entry support",
    ("risk", "trade_policy"):     "Trade risk monitoring + scenario planning",
    ("risk", "regulation"):       "Regulatory risk exposure report + remediation roadmap",
    ("intelligence", "m_and_a"):  "M&A target intelligence + due diligence support",
    ("intelligence", "technology"): "Technology landscape intelligence + competitive benchmarking",
}


# ── Event type normalization ──────────────────────────────────────────────────
# CausalChainResult.event_type is a free-form LLM string (e.g., "acquisition",
# "AI security acquisition", "technology_launch"). We need to map it to the
# known keys in _CONTACT_ROLES and _SERVICES.

_EVENT_TYPE_KEYWORDS: dict[str, list[str]] = {
    "trade_policy":   ["trade", "export", "import", "customs", "cross-border", "trade policy",
                       "duty", "anti-dumping", "quota", "embargo", "wto", "fta", "bilateral"],
    "supply_chain":   ["supply chain", "supplier", "sourcing", "logistics", "procurement", "shipping",
                       "inventory", "warehousing", "freight", "distribution", "vendor", "contract"],
    "price_change":   ["price", "cost", "tariff", "commodity", "inflation", "pricing", "revenue",
                       "profit", "margin", "buyback", "earnings", "valuation", "stock", "shares",
                       "decline", "drop", "surge", "rally", "quarterly", "annual result",
                       "dividend", "default", "guarantee", "debt", "bond", "credit"],
    "m_and_a":        ["acqui", "merger", "takeover", "buyout", "m&a", "consolidat", "funding",
                       "raise", "series a", "series b", "ipo", "invest", "stake", "joint venture",
                       "partnership", "deal", "billion", "million", "capital", "venture",
                       "private equity", "divestiture", "spinoff", "spin-off"],
    "regulation":     ["regulation", "regulatory", "compliance", "sanction", "ban", "law",
                       "policy", "government", "ministry", "rbi", "sebi", "sec", "fda",
                       "license", "approval", "mandate", "rule", "framework", "guideline",
                       "investigation", "probe", "penalty", "fine", "enforcement", "antitrust"],
    "technology":     ["technology", "tech", "ai ", "artificial intelligence", "software", "platform",
                       "digital", "cloud", "saas", "machine learning", "automation", "cyber", "iot",
                       "edge computing", "launch", "product", "innovation", "patent", "r&d",
                       "startup", "app ", "data", "analytics", "blockchain", "quantum",
                       "semiconductor", "chip", "gpu"],
    "labor":          ["labor", "workforce", "hiring", "layoff", "talent", "employee", "strike",
                       "attrition", "headcount", "remote work", "gig", "union"],
    "infrastructure": ["infrastructure", "facility", "plant", "construction", "warehouse",
                       "expansion", "expand", "capacity", "factory", "real estate", "port",
                       "rail", "highway", "energy", "power", "renewable", "solar", "wind"],
}


def _normalize_event_type(raw_event_type: str) -> str:
    """Map free-form LLM event_type to a known _CONTACT_ROLES key.

    Uses weighted keyword scanning with word-boundary awareness:
      - Multi-word phrases score 2 (more specific = higher weight)
      - Single-word keywords score 1
      - Short keywords (<=4 chars) require word boundaries to avoid
        substring false positives (e.g., "sec" matching "sector")
    The category with the highest total score wins.
    Falls back to "general" if no keywords match.
    """
    import re

    if not raw_event_type:
        return "general"

    # Direct match (rare but possible)
    lower = raw_event_type.lower().strip().replace("-", "_")
    if lower in _CONTACT_ROLES:
        return lower

    # Weighted keyword scoring — multi-word phrases worth 2x.
    # Short keywords use word-boundary regex to prevent "sec" in "sector" etc.
    best_key = "general"
    best_score = 0
    for key, keywords in _EVENT_TYPE_KEYWORDS.items():
        score = 0
        for kw in keywords:
            if " " in kw:
                # Multi-word phrase: simple substring match is safe
                if kw in lower:
                    score += 2
            elif len(kw) <= 4:
                # Short keyword: require word boundaries (arXiv:1909.00161 §3.2)
                if re.search(rf"\b{re.escape(kw)}\b", lower):
                    score += 1
            else:
                if kw in lower:
                    score += 1
        if score > best_score:
            best_score = score
            best_key = key

    return best_key


# ── Stage 1: Crystallize ──────────────────────────────────────────────────────

async def crystallize_leads(
    causal_result,                  # CausalChainResult from run_causal_council()
    trend_title: str,
    trend_summary: str,
    event_type: str,
    oss_score: float = 0.0,
) -> list[LeadSheet]:
    """
    Convert causal chain hops into concrete call-sheet leads.

    For each hop (above confidence threshold):
    1. Find real companies from hop.companies_found (already from KB)
       or fall back to KB search on hop.segment
    2. Build a LeadSheet with opening line, service pitch, contact role
    3. Enrich with company details (CIN, state, city) from KB

    Returns leads sorted by (confidence DESC, urgency_weeks ASC).
    """
    leads: list[LeadSheet] = []

    if not causal_result or not causal_result.hops:
        logger.warning("Lead crystallizer: no causal hops — returning empty")
        return leads

    for hop in causal_result.hops:
        if hop.confidence < 0.35:
            logger.debug(f"Skip hop {hop.hop}: confidence {hop.confidence:.2f} < 0.35")
            continue

        companies: list[str] = list(hop.companies_found) if hop.companies_found else []
        # Filter out entries that are descriptions rather than real company names.
        # The causal council LLM sometimes puts segment descriptions ("Mid-size
        # electrolyser manufacturers in India") in companies_found.
        before_filter = len(companies)
        companies = [c for c in companies if not is_company_description(c)]
        if before_filter > 0 and not companies:
            logger.info(
                f"Hop {hop.hop}: filtered {before_filter} description(s) from "
                f"companies_found (segment: {hop.segment[:60]})"
            )

        if not companies:
            # Don't use hop.segment as a company name — it's always a description.
            # Mark as placeholder so downstream skips it.
            companies = [f"[{hop.segment}]"]

        norm_type = _normalize_event_type(event_type)
        contact_role = _CONTACT_ROLES.get(norm_type, _CONTACT_ROLES["general"])
        service_key = (hop.lead_type, norm_type)
        service_pitch = _SERVICES.get(service_key, _default_service(hop.lead_type))

        for company_name in companies[:3]:   # Max 3 companies per hop (no spam)
            is_placeholder = company_name.startswith("[")

            lead = LeadSheet(
                company_name=company_name if not is_placeholder else hop.segment,
                company_state=_first_geo(hop.geo_hint),
                company_size_band=hop.employee_band,
                company_category="",
                hop=hop.hop,
                lead_type=hop.lead_type,
                trend_title=trend_title,
                event_type=norm_type,
                contact_role=contact_role,
                trigger_event=f"{trend_title} — {causal_result.event_summary[:80]}",
                pain_point=hop.mechanism,
                service_pitch=service_pitch,
                opening_line=_opening(
                    company_name if not is_placeholder else "Your business",
                    trend_title, hop.mechanism, hop.lead_type, hop.urgency_weeks,
                ),
                urgency_weeks=hop.urgency_weeks,
                confidence=hop.confidence * (0.8 if is_placeholder else 1.0),
                reasoning=causal_result.reasoning,
                data_sources=["causal_inference"],
                oss_score=oss_score,
            )
            leads.append(lead)

    leads.sort(key=lambda l: (-l.confidence, l.urgency_weeks))
    logger.info(f"Crystallized {len(leads)} leads from {len(causal_result.hops)} hops")
    return leads


def _opening(company: str, trend: str, mechanism: str, lead_type: str, weeks: int) -> str:
    if lead_type == "pain":
        return (
            f"{company} faces a concrete challenge: {mechanism}. "
            f"This will likely materialize within {weeks} weeks. "
            f"We help companies navigate exactly this kind of pressure."
        )
    elif lead_type == "opportunity":
        return (
            f"The recent {trend.lower()} creates a specific opening for {company}. "
            f"{mechanism}. "
            f"Companies that move in the next {weeks} weeks capture the most value."
        )
    elif lead_type == "risk":
        return (
            f"{company} carries elevated risk right now: {mechanism}. "
            f"Our risk intelligence platform can help quantify and mitigate this exposure."
        )
    else:
        return (
            f"Given the recent {trend.lower()}, {company} stands to benefit from "
            f"sharper competitive intelligence. {mechanism}."
        )


def _first_geo(geo_hint: str) -> str:
    if not geo_hint:
        return ""
    return geo_hint.split(",")[0].strip()


def _default_service(lead_type: str) -> str:
    if lead_type == "pain":
        return "Market intelligence + strategic advisory"
    elif lead_type == "opportunity":
        return "Opportunity intelligence + execution support"
    else:
        return "Business intelligence + risk monitoring"


# ── Stage 2: Lead Gen (contact + email enrichment) ────────────────────────────

class LeadGenResult(BaseModel):
    """Structured output from the Lead Gen Agent."""
    companies_found: int = 0
    contacts_found: int = 0
    emails_generated: int = 0
    outreach_generated: int = 0
    low_relevance_filtered: int = 0
    reasoning: str = ""


async def _resolve_domain(company_name: str, mock_mode: bool = False) -> str:
    """Find a company's domain via Clearbit → web search → validation.

    Clearbit Autocomplete (FREE, no auth, <100ms) is tried first since
    it reliably maps company names to canonical domains. Falls back to
    web search when Clearbit doesn't know the company.
    """
    if mock_mode:
        from app.tools.domain_utils import extract_domain_from_company_name
        return extract_domain_from_company_name(company_name) or ""

    # Step 1: Clearbit Autocomplete — free, instant, reliable for known companies
    try:
        import httpx
        async with httpx.AsyncClient(timeout=5.0) as client:
            resp = await client.get(
                "https://autocomplete.clearbit.com/v1/companies/suggest",
                params={"query": company_name},
            )
            if resp.status_code == 200:
                results = resp.json()
                if results and isinstance(results, list):
                    first = results[0]
                    domain = first.get("domain", "")
                    if domain:
                        return domain
    except Exception as e:
        logger.debug(f"Clearbit domain lookup failed for '{company_name}': {e}")

    # Step 2: Web search fallback (Tavily → DDG)
    try:
        from app.tools.web.web_intel import search
        from app.tools.domain_utils import extract_clean_domain, is_valid_company_domain

        results = await search(f"{company_name} official website", max_results=5)
        for r in results:
            d = extract_clean_domain(r.url)
            if d and is_valid_company_domain(d):
                return d
    except Exception as e:
        logger.debug(f"Domain resolution for '{company_name}' failed: {e}")
    return ""


async def _build_companies_from_leads(
    deps: AgentDeps,
    lead_sheets: list,
) -> list:
    """Build CompanyData objects from unique company names in lead sheets.

    Also:
    - Assigns target_roles from lead event_type via match_roles_to_trend()
    - Propagates verification data (ner_verified, verification_confidence)
      from company_enricher validation results
    """
    from app.schemas.sales import CompanyData
    from app.agents.workers.contact_agent import match_roles_to_trend

    seen: dict[str, Any] = {}
    # Map company_name -> lead sheet for post-build target_roles assignment
    lead_by_company: dict[str, Any] = {}
    sem = asyncio.Semaphore(5)

    async def _build_one(name: str, lead):
        async with sem:
            if name in seen:
                return
            try:
                from app.database import get_database
                db = get_database()
                cached = db.get_or_enrich_company(name, max_age_days=7)
                if cached and (cached.get("description") or cached.get("headquarters") or cached.get("wikidata_id")):
                    cid = cached["id"]
                    seen[name] = CompanyData(
                        id=cid,
                        company_name=name,
                        industry=cached.get("industry") or lead.event_type or "general",
                        domain=cached.get("domain", ""),
                        website=cached.get("website", ""),
                        description=cached.get("description", ""),
                        headquarters=cached.get("headquarters", ""),
                        employee_count=cached.get("employee_count", ""),
                        stock_ticker=cached.get("stock_ticker", ""),
                        ceo=cached.get("ceo", ""),
                        founded_year=cached.get("founded_year"),
                        wikidata_id=cached.get("wikidata_id", ""),
                        reason_relevant=lead.pain_point or lead.trend_title,
                        trend_id=str(lead.trend_title),
                        # KB cache has validated data — mark as verified
                        ner_verified=True,
                        verification_source="kb_cache",
                        verification_confidence=0.85,
                    )
                    logger.info(f"  KB hit for {name} — skipping enrichment")
                    return
            except Exception:
                pass

            domain = await _resolve_domain(name, mock_mode=deps.mock_mode)
            cid = hashlib.md5(name.lower().encode()).hexdigest()[:12]
            try:
                seen[name] = CompanyData(
                    id=cid,
                    company_name=name,
                    industry=lead.event_type or "general",
                    domain=domain,
                    website=f"https://{domain}" if domain else "",
                    reason_relevant=lead.pain_point or lead.trend_title,
                    trend_id=str(lead.trend_title),
                )
            except Exception as e:
                logger.debug(f"CompanyData validation failed for '{name}': {e}")
                return
            if domain:
                logger.info(f"  Resolved domain: {name} → {domain}")
            else:
                logger.debug(f"  No domain found for: {name}")

    tasks = []
    for lead in lead_sheets:
        name = lead.company_name
        # Skip placeholders and segment descriptions (not real company names)
        if not name or name.startswith("[") or len(name) > 100:
            continue
        # Guard: reject names that are actually segment descriptions
        if is_company_description(name):
            logger.info(f"Skipping description-as-name: '{name[:80]}'")
            continue
        if name not in lead_by_company:
            lead_by_company[name] = lead
        if name not in seen:
            tasks.append(_build_one(name, lead))

    if tasks:
        await asyncio.gather(*tasks, return_exceptions=True)

    companies = list(seen.values())
    to_enrich = [c for c in companies if not c.description and not getattr(c, "wikidata_id", "")]
    if to_enrich:
        try:
            from app.tools.company_enricher import enrich

            enrich_sem = asyncio.Semaphore(5)

            async def _do_enrich(c: "CompanyData"):
                async with enrich_sem:
                    try:
                        enriched = await asyncio.wait_for(
                            enrich(c.company_name, domain=c.domain, skip_validation=True),
                            timeout=8.0,
                        )
                        if enriched:
                            c.description = enriched.description or c.description
                            c.headquarters = enriched.headquarters or getattr(c, "headquarters", "")
                            c.employee_count = enriched.employee_count or getattr(c, "employee_count", "")
                            c.stock_ticker = enriched.stock_ticker or getattr(c, "stock_ticker", "")
                            c.ceo = enriched.ceo or getattr(c, "ceo", "")
                            c.founded_year = enriched.founded_year or getattr(c, "founded_year", None)
                            c.wikidata_id = enriched.wikidata_id or getattr(c, "wikidata_id", "")
                            c.industry = enriched.industry or c.industry
                            if enriched.domain and not c.domain:
                                c.domain = enriched.domain
                                c.website = f"https://{enriched.domain}"
                            # Propagate validation -> verification fields
                            if enriched.validation:
                                v = enriched.validation
                                if v.is_valid_company:
                                    c.ner_verified = True
                                    c.verification_confidence = max(
                                        c.verification_confidence, v.confidence
                                    )
                                    c.verification_source = (
                                        c.verification_source or v.validation_source
                                    )
                                elif not c.ner_verified:
                                    # Enrichment returned but entity not validated
                                    c.verification_confidence = max(
                                        c.verification_confidence, 0.4
                                    )
                                    c.verification_source = (
                                        c.verification_source or "enriched_unvalidated"
                                    )
                    except Exception as e:
                        logger.debug(f"Enrichment failed for {c.company_name}: {e}")

            results = await asyncio.gather(*[_do_enrich(c) for c in to_enrich], return_exceptions=True)
            err_count = sum(1 for r in results if isinstance(r, Exception))
            if err_count:
                logger.debug(f"Enrichment: {err_count}/{len(to_enrich)} companies had errors")
            enriched_count = sum(1 for c in to_enrich if c.description)
            logger.info(f"  Enriched {enriched_count}/{len(to_enrich)} companies via company_enricher")
        except Exception as e:
            logger.debug(f"Batch enrichment failed: {e}")

    # Assign target_roles from lead event_type + trend context
    roles_assigned = 0
    for c in companies:
        if c.target_roles:
            continue  # Already has roles (e.g., from KB)
        lead = lead_by_company.get(c.company_name)
        if not lead:
            continue
        roles = match_roles_to_trend(
            trend_type=lead.event_type or "general",
            pain_point=lead.pain_point or "",
            trend_title=lead.trend_title or "",
        )
        if roles:
            c.target_roles = roles
            roles_assigned += 1
    if roles_assigned:
        logger.info(f"  Assigned target_roles to {roles_assigned}/{len(companies)} companies")

    return companies


def _build_person_profiles(
    contacts: list,
    outreach_emails: list,
    impacts: list,
    companies: list,
) -> list:
    """Build PersonProfile objects from contacts + outreach, with reach scores."""
    from app.schemas.sales import PersonProfile
    from app.agents.workers.contact_agent import ContactFinder

    outreach_by_contact = {}
    for em in outreach_emails:
        cid = getattr(em, "contact_id", "")
        if cid:
            outreach_by_contact[cid] = em

    impact_roles: dict[str, set] = {}
    for imp in impacts:
        tid = getattr(imp, "trend_id", "")
        roles = {r.lower() for r in getattr(imp, "target_roles", [])}
        impact_roles[tid] = roles
        # Also key by trend_title (company.trend_id is set to trend_title
        # in the lead gen path, not the actual trend UUID)
        ttitle = getattr(imp, "trend_title", "")
        if ttitle:
            impact_roles[ttitle] = roles

    # Map company_name -> (trend_id, target_roles from CompanyData)
    company_trend: dict[str, str] = {}
    company_roles: dict[str, set] = {}
    for c in companies:
        cname = getattr(c, "company_name", "")
        company_trend[cname] = getattr(c, "trend_id", "")
        croles = getattr(c, "target_roles", [])
        if croles:
            company_roles[cname] = {r.lower() for r in croles}

    profiles = []
    for ct in contacts:
        try:
            tier = ContactFinder.classify_tier(ct.role)
            tone = ContactFinder.get_outreach_tone(tier)

            trend_id = company_trend.get(ct.company_name, "")
            target_roles = impact_roles.get(trend_id, set())
            # Fallback: use company's own target_roles (populated from lead event_type)
            if not target_roles:
                target_roles = company_roles.get(ct.company_name, set())
            role_relevance = 0.7 if ct.role.lower() in target_roles else 0.3

            reach = ContactFinder.compute_reach_score(
                email=ct.email,
                email_confidence=ct.email_confidence,
                verified=ct.verified,
                linkedin_url=ct.linkedin_url,
                seniority_tier=tier,
                role_relevance=role_relevance,
            )

            outreach = outreach_by_contact.get(ct.id)

            profiles.append(PersonProfile(
                id=ct.id,
                company_id=ct.company_id,
                company_name=ct.company_name,
                person_name=ct.person_name,
                role=ct.role,
                seniority_tier=tier,
                linkedin_url=ct.linkedin_url,
                email=ct.email,
                email_confidence=ct.email_confidence,
                email_source=ct.email_source,
                verified=ct.verified,
                reach_score=reach,
                outreach_tone=tone,
                outreach_subject=getattr(outreach, "subject", "") if outreach else "",
                outreach_body=getattr(outreach, "body", "") if outreach else "",
            ))
        except Exception as e:
            logger.warning(f"Failed to build profile for {getattr(ct, 'person_name', '?')}: {e}")
            continue

    tier_order = {"decision_maker": 0, "influencer": 1, "gatekeeper": 2}
    profiles.sort(key=lambda p: (tier_order.get(p.seniority_tier, 1), -p.reach_score))
    return profiles


async def run_lead_gen(deps: AgentDeps) -> tuple:
    """Enrich pre-resolved lead sheets with contacts and emails.

    Returns (companies, contacts, outreach, result).
    """
    lead_sheets = getattr(deps, "_lead_sheets", [])
    if not lead_sheets:
        logger.warning("Lead gen: no lead sheets from crystallizer — skipping enrichment")
        return [], [], [], LeadGenResult(reasoning="No lead sheets to enrich")

    logger.info(f"Lead gen: enriching {len(lead_sheets)} lead sheets")
    agent_reasoning_parts = []

    try:
        companies = await asyncio.wait_for(
            _build_companies_from_leads(deps, lead_sheets),
            timeout=300.0,
        )
        deps._companies = companies
        with_domain = sum(1 for c in companies if c.domain)
        agent_reasoning_parts.append(
            f"Resolved {len(companies)} companies ({with_domain} with domain)"
        )
        logger.info(f"Lead gen: {len(companies)} companies, {with_domain} with domain")
    except asyncio.TimeoutError:
        logger.warning("Lead gen: domain resolution timed out")
        deps._companies = []
        agent_reasoning_parts.append("Domain resolution timed out")
    except Exception as e:
        logger.error(f"Lead gen: company build failed: {e}")
        deps._companies = []
        agent_reasoning_parts.append(f"Company build error: {e}")

    if deps._companies:
        try:
            from app.agents.workers.contact_agent import ContactFinder
            from app.schemas import AgentState

            finder = ContactFinder(mock_mode=deps.mock_mode, deps=deps)
            state = AgentState(
                trends=deps._trend_data,
                impacts=deps._impacts,
                companies=deps._companies,
            )
            from app.config import get_settings as _gs
            _contact_timeout = _gs().lead_gen_timeout * 0.6  # 60% of lead_gen budget
            result = await asyncio.wait_for(
                finder.find_contacts(state), timeout=_contact_timeout,
            )
            deps._contacts = result.contacts or []
            with_email = sum(1 for c in deps._contacts if getattr(c, "email", ""))
            agent_reasoning_parts.append(
                f"Found {len(deps._contacts)} contacts ({with_email} with email)"
            )
            if deps._contacts and with_email == 0:
                logger.warning(
                    f"Lead gen: {len(deps._contacts)} contacts found but 0 have emails. "
                    f"Check Apollo API key (403?) and Hunter fallback."
                )
        except asyncio.TimeoutError:
            logger.warning("Lead gen: contact search timed out")
            agent_reasoning_parts.append("Contact search timed out")
        except Exception as e:
            logger.error(f"Lead gen: contact search failed: {e}")
            agent_reasoning_parts.append(f"Contact error: {e}")

    if deps._contacts:
        try:
            from app.agents.workers.email_agent import EmailGenerator
            from app.schemas import AgentState

            generator = EmailGenerator(mock_mode=deps.mock_mode, deps=deps)
            state = AgentState(
                trends=deps._trend_data,
                companies=deps._companies,
                contacts=deps._contacts,
            )
            result = await asyncio.wait_for(
                generator.process_emails(state), timeout=180.0,
            )
            deps._contacts = result.contacts or deps._contacts
            deps._outreach = result.outreach_emails or []
            agent_reasoning_parts.append(
                f"Generated {len(deps._outreach)} outreach emails"
            )
        except asyncio.TimeoutError:
            logger.warning("Lead gen: email generation timed out")
            agent_reasoning_parts.append("Email generation timed out")
        except Exception as e:
            logger.error(f"Lead gen: email generation failed: {e}")
            agent_reasoning_parts.append(f"Email error: {e}")

    logger.info(
        f"Lead gen step 4: building profiles from "
        f"{len(deps._contacts)} contacts, {len(deps._outreach)} outreach, "
        f"{len(deps._impacts)} impacts, {len(deps._companies)} companies"
    )
    try:
        profiles = _build_person_profiles(
            contacts=deps._contacts,
            outreach_emails=deps._outreach,
            impacts=deps._impacts,
            companies=deps._companies,
        )
        deps._person_profiles = profiles
        dm_count = sum(1 for p in profiles if p.seniority_tier == "decision_maker")
        inf_count = sum(1 for p in profiles if p.seniority_tier == "influencer")
        logger.info(f"Lead gen step 4: built {len(profiles)} profiles ({dm_count} DMs, {inf_count} inf)")
        agent_reasoning_parts.append(
            f"Built {len(profiles)} person profiles ({dm_count} DMs, {inf_count} influencers)"
        )
    except Exception as e:
        logger.error(f"Lead gen: person profile build failed: {e}", exc_info=True)
        deps._person_profiles = []
        agent_reasoning_parts.append(f"Profile build error: {e}")

    agent_result = LeadGenResult(
        companies_found=len(deps._companies),
        contacts_found=len(deps._contacts),
        emails_generated=len(deps._outreach),
        outreach_generated=len(deps._outreach),
        reasoning=" | ".join(agent_reasoning_parts) or "No data produced",
    )

    logger.info(
        f"Lead gen complete: {agent_result.companies_found} companies, "
        f"{agent_result.contacts_found} contacts, "
        f"{agent_result.outreach_generated} outreach"
    )

    return deps._companies, deps._contacts, deps._outreach, agent_result
